name: Development Preview

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Start development server
      run: |
        npx live-server --port=8080 --no-browser &
        sleep 5
        curl -f http://localhost:8080 || exit 1
        
    - name: Comment preview URL
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: `🔧 **Development Preview Available**
            
Preview URL: ${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/deployments/activity_log?environment=github-pages
            
This is a development build. Changes may be experimental.`
          });
